- id: '1675712583101'
  alias: Level Display Button Toggle
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.level_display_button
    to: 'on'
  condition: []
  action:
  - service: input_boolean.toggle
    data: {}
    target:
      entity_id: input_boolean.level_display_switch
  mode: single
- id: '1675963006760'
  alias: Level Display Switch Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.level_display_switch
    to: 'off'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      device_id: 4fe16d05ffeaa62033641715a8a8df30
  mode: single
- id: '1675963415480'
  alias: Level Display Pitch
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.level_sensor_pitch_trimmed
  condition:
  - condition: state
    entity_id: input_boolean.level_display_switch
    state: 'on'
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.level_sensor_pitch_trimmed
        above: 4
      sequence:
      - service: light.turn_on
        data:
          color_name: yellow
        target:
          entity_id: light.level_display_part_1
      - service: light.turn_off
        data: {}
        target:
          entity_id:
          - light.level_display_part_2
          - light.level_display_part_3
    - conditions:
      - condition: numeric_state
        entity_id: sensor.level_sensor_pitch_trimmed
        above: 2
        below: 4
      sequence:
      - service: light.turn_on
        data:
          color_name: yellow
          brightness_pct: 50
        target:
          entity_id: light.level_display_part_1
      - service: light.turn_on
        data:
          color_name: green
          brightness_pct: 50
        target:
          entity_id: light.level_display_part_2
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.level_display_part_3
    - conditions:
      - condition: numeric_state
        entity_id: sensor.level_sensor_pitch_trimmed
        above: -2
        below: 2
      sequence:
      - service: light.turn_on
        data:
          color_name: green
        target:
          entity_id: light.level_display_part_2
      - service: light.turn_off
        data: {}
        target:
          entity_id:
          - light.level_display_part_1
          - light.level_display_part_3
    - conditions:
      - condition: numeric_state
        entity_id: sensor.level_sensor_pitch_trimmed
        above: -4
        below: -2
      sequence:
      - service: light.turn_on
        data:
          color_name: red
          brightness_pct: 50
        target:
          entity_id: light.level_display_part_3
      - service: light.turn_on
        data:
          color_name: green
          brightness_pct: 50
        target:
          entity_id: light.level_display_part_2
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.level_display_part_1
    - conditions:
      - condition: numeric_state
        entity_id: sensor.level_sensor_pitch_trimmed
        below: -4
      sequence:
      - service: light.turn_on
        data:
          color_name: red
        target:
          entity_id: light.level_display_part_3
      - service: light.turn_off
        data: {}
        target:
          entity_id:
          - light.level_display_part_1
          - light.level_display_part_2
  mode: single
- id: '1675963902468'
  alias: Level Display Roll
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.level_sensor_roll_trimmed
  condition:
  - condition: state
    entity_id: input_boolean.level_display_switch
    state: 'on'
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.level_sensor_roll_trimmed
        above: 4
      sequence:
      - service: light.turn_on
        data:
          color_name: yellow
        target:
          entity_id: light.level_display_part_4
      - service: light.turn_off
        data: {}
        target:
          entity_id:
          - light.level_display_part_5
          - light.level_display_part_6
    - conditions:
      - condition: numeric_state
        entity_id: sensor.level_sensor_roll_trimmed
        above: 2
        below: 4
      sequence:
      - service: light.turn_on
        data:
          color_name: yellow
          brightness_pct: 50
        target:
          entity_id:
          - light.level_display_part_4
      - service: light.turn_on
        data:
          color_name: green
          brightness_pct: 50
        target:
          entity_id: light.level_display_part_5
      - service: light.turn_off
        data: {}
        target:
          entity_id:
          - light.level_display_part_6
    - conditions:
      - condition: numeric_state
        entity_id: sensor.level_sensor_roll_trimmed
        above: -2
        below: 2
      sequence:
      - service: light.turn_on
        data:
          color_name: green
        target:
          entity_id: light.level_display_part_5
      - service: light.turn_off
        data: {}
        target:
          entity_id:
          - light.level_display_part_4
          - light.level_display_part_6
    - conditions:
      - condition: numeric_state
        entity_id: sensor.level_sensor_roll_trimmed
        below: -2
        above: -4
      sequence:
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.level_display_part_4
      - service: light.turn_on
        data:
          color_name: green
          brightness_pct: 50
        target:
          entity_id: light.level_display_part_5
      - service: light.turn_on
        data:
          color_name: red
          brightness_pct: 50
        target:
          entity_id: light.level_display_part_6
    - conditions:
      - condition: numeric_state
        entity_id: sensor.level_sensor_roll_trimmed
        below: -4
      sequence:
      - service: light.turn_off
        data: {}
        target:
          entity_id:
          - light.level_display_part_4
          - light.level_display_part_5
      - service: light.turn_on
        data:
          color_name: red
        target:
          entity_id: light.level_display_part_6
  mode: single
- id: '1693610638071'
  alias: Converter Energy Meter Force Update If Unavailable
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.converter_energy_meter'') == ''unavailable''
      }}'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id:
      - sensor.converter_energy
      - sensor.converter_energy_meter
  mode: single
