
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

recorder: !include recorder.yaml

automation: !include automations.yaml
command_line: !include_dir_merge_list command_line
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensor
template: !include_dir_merge_list template

remote_homeassistant:
  instances:

shell_command: !include shell_command.yaml

# Load custom services for setting timezone, etc.
#arvee: